### ISSUE TITLE
overflow isn't handled gracefully

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/mla-admin-bar#2]
On some sites with long names, like Computer Studies in Language and Literature, the name of the group is so long in the breadcrumb that the admin bar overflows, and not very gracefully. Although this only happens on certain widths (in this case, < 1000px), this would be good to fix eventually. Options for fixing would be: 
- truncate and add an ellipsis to long group names greater than a certain number of characters
- remove this breadcrumb in admin views entirely

**Comment by susanasevilla** [comment]
This issue is being taken up elsewhere
